name: Test Toot

on:
  workflow_dispatch:
      
  
jobs:
  print-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Report to Mastodon
      uses: cbrgm/mastodon-github-action@v1.0.1
      env:
        MASTODON_URL: ${{ secrets.MASTODON_URL }}
        MASTODON_ACCESS_TOKEN: ${{ secrets.MASTODON_ACCESS_TOKEN }}
      with:
        message: |
          This is a test toot, automatically posted by a github action.
          https://github.com/iluvcapra/ptulsconv
